// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: proto/link_station.proto

package link_station

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_link_station_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_link_station_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_link_station_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type LinkStation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32   `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32   `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	R int32   `protobuf:"varint,3,opt,name=r,proto3" json:"r,omitempty"`
	P float32 `protobuf:"fixed32,4,opt,name=p,proto3" json:"p,omitempty"`
}

func (x *LinkStation) Reset() {
	*x = LinkStation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_link_station_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkStation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStation) ProtoMessage() {}

func (x *LinkStation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_link_station_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStation.ProtoReflect.Descriptor instead.
func (*LinkStation) Descriptor() ([]byte, []int) {
	return file_proto_link_station_proto_rawDescGZIP(), []int{1}
}

func (x *LinkStation) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *LinkStation) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *LinkStation) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *LinkStation) GetP() float32 {
	if x != nil {
		return x.P
	}
	return 0
}

var File_proto_link_station_proto protoreflect.FileDescriptor

var file_proto_link_station_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22,
	0x45, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x70, 0x32, 0x3a, 0x0a, 0x12, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x12, 0x06, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x1a, 0x0c, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_link_station_proto_rawDescOnce sync.Once
	file_proto_link_station_proto_rawDescData = file_proto_link_station_proto_rawDesc
)

func file_proto_link_station_proto_rawDescGZIP() []byte {
	file_proto_link_station_proto_rawDescOnce.Do(func() {
		file_proto_link_station_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_link_station_proto_rawDescData)
	})
	return file_proto_link_station_proto_rawDescData
}

var file_proto_link_station_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_link_station_proto_goTypes = []interface{}{
	(*Point)(nil),       // 0: Point
	(*LinkStation)(nil), // 1: LinkStation
}
var file_proto_link_station_proto_depIdxs = []int32{
	0, // 0: LinkStationService.GetNearest:input_type -> Point
	1, // 1: LinkStationService.GetNearest:output_type -> LinkStation
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_link_station_proto_init() }
func file_proto_link_station_proto_init() {
	if File_proto_link_station_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_link_station_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_link_station_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkStation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_link_station_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_link_station_proto_goTypes,
		DependencyIndexes: file_proto_link_station_proto_depIdxs,
		MessageInfos:      file_proto_link_station_proto_msgTypes,
	}.Build()
	File_proto_link_station_proto = out.File
	file_proto_link_station_proto_rawDesc = nil
	file_proto_link_station_proto_goTypes = nil
	file_proto_link_station_proto_depIdxs = nil
}
